client:
  server_address: 127.0.0.1:8008
  test: False

server:
  server_address: 127.0.0.1:8008
  strategy: fedavg
  num_rounds: 15


common:
  model: cnn
  data: cifar
  advanced_name: cifar10_iid
  split: True
  cuda: False